### ISSUE TITLE
Composer cant find Php-oara

### ISSUE THREAD

**Issue by LTKort** [padosoft/laravel-affiliate-network#3]
See;

git@github.com:fubralimited/php-oara.git                                   
    Cloning into '//vendor/fubralimited/php-oara'...                                                              
    ERROR: Repository not found.                                               
    fatal: Could not read from remote repository.

**Comment by PaoloNardini** [comment]
Hi!
fubralimited/php-oara seems to not exists anymore.
It seems to be moved under robryanx/php-oara

Although, padosoft/laravel-affiliate-network don't depends on this package, we have our own fork at padosoft/php-oara.

Regards.

**Comment by dansleboby** [comment]
I have an updated version, just before they remove it

https://github.com/dansleboby/php-oara
