### ISSUE TITLE
zanox and Affiliate Window rebrand to Awin

### ISSUE THREAD

**Issue by Ezyweb-uk** [padosoft/laravel-affiliate-network#6]
When searching for zanox I found this post [zanox and Affiliate Window rebrand to Awin](https://www.awin.com/gb/news-and-events/awin-news/zanox-and-affiliate-window-rebrand-to-awin). Does the affiliate network code need refactoring?

**Comment by PaoloNardini** [comment]
Yes, Zanox has been acquired by Awin, and all the previous ads campaigns run by Zanox are slowly  migrating to Awin, but, in the meanwhile, the old Zanox api is still running until there are active campaigns. The old Zanox  API will be completely dismissed when no running campaigns are left and all the campaigns will be available through the Awin API.
So, no refactoring is needed, simply the Zanox api will become unuseful.
Does it make sense?

**Comment by Ezyweb-uk** [comment]
PaoloNardini thank you for your explanation, much appreciated.
